name: pnpm CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }},
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }},
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }},
      GOOGLE_ID: ${{ secrets.GOOGLE_ID }},
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }},
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }},
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }},
      AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER }},

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run Type Check
        run: pnpm run typecheck
      - name: Run Lint
        run: pnpm run lint
      - name: Run Build
        run: pnpm run build
