name: pnpm CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }},
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }},
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }},
      GOOGLE_ID: ${{ secrets.GOOGLE_ID }},
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }},
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }},
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }},
      AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER }},
      EMAIL_SERVER_USER: ${{ secrets.EMAIL_SERVER_USER }},
      EMAIL_SERVER_PASSWORD: ${{ secrets.EMAIL_SERVER_PASSWORD }},
      EMAIL_SERVER_HOST: ${{ secrets.EMAIL_SERVER_HOST }},
      EMAIL_SERVER_PORT: ${{ secrets.EMAIL_SERVER_PORT }},
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }},

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run Type Check
        run: pnpm run typecheck
      - name: Run Lint
        run: pnpm run lint
      - name: Run Build
        run: pnpm run build
